### ISSUE TITLE
gulp example broken

### ISSUE THREAD

**Issue by rejas** [itgalaxy/favicons#272]
Hi, with v5.4 your gulp example in the README throws the following error when run:

```
[12:29:51] TypeError: (config.html[platform] || []).map is not a function
    at createHTML (/Users/rejas/Projects/rejas.de/node_modules/favicons/dist/index.js:118:54)
```

What has changed in the way one has to provide a config to favicons?

**Comment by echavaillaz** [comment]
Yes, I can confirm this bug...

**Comment by chrbala** [comment]
It's caused by ad4816c. ``return Promise.all((config.html[platform] || []).map(µ.HTML.render));``. config.html[platform] is an object, so it does not have a map function. 

It should be reverted back to something like:
```
Promise.all(
  Object.values(config.html[platform] || {}).map(µ.HTML.parse)
);
```

I'm still getting errors with that though, because it seems that something was changes with regard to the rendering here. I'm not sure exactly what though, so for now I'll stay pinned on version 5.3.0.

**Comment by rejas** [comment]
Seems to be fixed with latest version 5.4.1
